const { chromium } = require('C:/Users/Sherwin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')

;(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' })
  const errors = []
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 })
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
  await page.evaluate(() => localStorage.clear())
  await page.reload({ waitUntil: 'networkidle' })
  const title = await page.locator('h1').first().innerText()
  const regions = await page.locator('header, main > section, footer').count()
  const overflowDesktop = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  await page.screenshot({ path: 'artifacts/home-desktop.png', fullPage: true })

  await page.getByRole('link', { name: 'Student login' }).first().click()
  await page.getByRole('button', { name: /Continue securely/i }).click()
  await page.waitForURL('**/onboarding/exams')
  const preSelectionTabs = await page.locator('[role="tab"]').count()
  await page.getByRole('button', { name: 'Select CUET UG' }).click()
  await page.getByRole('button', { name: /Continue with selected exams/i }).click()
  await page.waitForURL('**/workspace/cuet-ug')
  await page.getByRole('tab', { name: 'CUET UG' }).waitFor()
  const tabLabels = await page.locator('[role="tab"]').allInnerTexts()
  await page.reload({ waitUntil: 'networkidle' })
  const persistedTabs = await page.locator('[role="tab"]').allInnerTexts()

  const scenario = await browser.newPage({ viewport: { width: 1280, height: 900 } })
  scenario.on('pageerror', e => errors.push(e.message))
  await scenario.goto('http://127.0.0.1:5173/login', { waitUntil: 'networkidle' })
  await scenario.evaluate(() => localStorage.clear())
  await scenario.reload({ waitUntil: 'networkidle' })
  await scenario.getByRole('button', { name: /Continue securely/i }).click()
  await scenario.getByRole('button', { name: 'Select JEE Main' }).click()
  await scenario.getByRole('button', { name: 'Select NEET UG' }).click()
  await scenario.getByRole('button', { name: /Continue with selected exams/i }).click()
  await scenario.getByRole('tab', { name: 'JEE Main' }).waitFor()
  const multiTabs = await scenario.locator('[role="tab"]').allInnerTexts()

  await scenario.goto('http://127.0.0.1:5173/apply/jee-main/0')
  await scenario.getByLabel('Candidate name').fill('JEE Candidate')
  await scenario.getByRole('checkbox').check()
  await scenario.getByRole('button', { name: /Save and continue/i }).click()
  await scenario.goto('http://127.0.0.1:5173/apply/neet-ug/0')
  await scenario.getByLabel('Candidate name').fill('NEET Candidate')
  await scenario.getByRole('checkbox').check()
  await scenario.getByRole('button', { name: /Save and continue/i }).click()
  const isolatedAnswers = await scenario.evaluate(() => {
    const data = JSON.parse(localStorage.getItem('nta-citizen-first-v1'))
    return [data.applications['jee-main'].answers.fullName, data.applications['neet-ug'].answers.fullName]
  })

  await scenario.goto('http://127.0.0.1:5173/onboarding/exams?mode=add')
  await scenario.getByRole('button', { name: 'Select CUET UG' }).click()
  await scenario.getByRole('button', { name: /Continue with selected exams/i }).click()
  await scenario.getByRole('tab', { name: 'CUET UG' }).waitFor()
  const addedTabs = await scenario.locator('[role="tab"]').allInnerTexts()

  const mobile = await browser.newPage({ viewport: { width: 360, height: 800 }, deviceScaleFactor: 1 })
  mobile.on('pageerror', e => errors.push(e.message))
  await mobile.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
  const overflowMobile = await mobile.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  await mobile.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true })

  console.log(JSON.stringify({ title, regions, overflowDesktop, overflowMobile, preSelectionTabs, tabLabels, persistedTabs, multiTabs, isolatedAnswers, addedTabs, errors }, null, 2))
  await browser.close()
})().catch(err => { console.error(err); process.exit(1) })
