import { useMemo, useState } from 'react'
import { Link, Navigate, useLocation, useNavigate, useParams } from 'react-router-dom'
import { AlertCircle, ArrowLeft, ArrowRight, BookOpen, CalendarDays, Check, CheckCircle2, ChevronRight, Clock3, CreditCard, Download, ExternalLink, FileCheck2, FileText, GraduationCap, HelpCircle, LocateFixed, LockKeyhole, Megaphone, PlayCircle, Search, ShieldCheck, Sparkles, UserRound, WalletCards } from 'lucide-react'
import { Carousel, EmptyState, ExamCard, ExternalAnchor, Footer, Header, Status, WorkspaceShell } from './components'
import { ecosystem, exams, getExam, getSteps } from './data'
import { useApp } from './state/AppState'

const deepExams = exams.filter(e => e.steps)

export function Home() {
  return <div className="public-page"><Header/><main><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> A clearer path for every student</span><h1>Every exam.<br/><em>One clear place.</em></h1><p>Discover NTA examinations, prepare with official resources, and keep every application milestone organized from one student workspace.</p><div className="hero-actions"><Link className="primary-btn large" to="/exams">Explore exams <ArrowRight size={18}/></Link><Link className="secondary-btn large" to="/login">Student login</Link></div><div className="trust-note"><ShieldCheck size={18}/><span><strong>Independent prototype</strong> · No connection to private government systems</span></div></div>
    <div className="hero-visual" aria-label="Student exam planning illustration"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="student-card"><div className="student-card-head"><span className="avatar"><UserRound/></span><span><small>YOUR EXAM PLAN</small><strong>Ready for what’s next</strong></span><CheckCircle2/></div><div className="progress-row"><span>Profile readiness</span><b>72%</b></div><div className="progress-bar"><span/></div><div className="mini-step done"><Check/> Profile details reviewed</div><div className="mini-step"><CalendarDays/> Pick your examinations</div></div><div className="float-chip chip-one"><Clock3/> 3 milestones ahead</div><div className="float-chip chip-two"><ShieldCheck/> Private by design</div></div>
    <div className="hero-tools"><a href="https://nta.ac.in/Quiz" target="_blank" rel="noreferrer" className="tool-card"><span className="tool-icon blue"><PlayCircle/></span><span><small>OFFICIAL MOCK TEST</small><strong>Practice the CBT interface</strong><em>Open mock tests <ExternalLink size={14}/></em></span></a><a href="https://www.nta.ac.in/abhyas" target="_blank" rel="noreferrer" className="tool-card"><span className="tool-icon purple"><BookOpen/></span><span><small>NATIONAL TEST ABHYAS</small><strong>Practice and review performance</strong><em>Explore Abhyas <ExternalLink size={14}/></em></span></a></div>
    </section><Carousel items={ecosystem}/></main><Footer/></div>
}

export function Login() {
  const { state, login, reset } = useApp(); const navigate = useNavigate(); const location = useLocation()
  const submit = e => { e.preventDefault(); login(); const target = state.profile.selectedExamIds.length ? '/dashboard' : '/onboarding/exams'; navigate(location.state?.from?.pathname || target, { replace: true }) }
  return <div className="auth-page"><Header/><main className="auth-main"><section className="login-panel"><div className="login-intro"><span className="eyebrow">Student workspace</span><h1>Your exam journey,<br/>without the guesswork.</h1><p>This safe demo uses a synthetic student profile. No OTP, government login, or personal data is involved.</p><ul><li><Check/> Select only the exams that matter to you</li><li><Check/> Keep each application’s progress separate</li><li><Check/> Find official resources in context</li></ul></div><form className="login-card" onSubmit={submit}><span className="lock-icon"><LockKeyhole/></span><h2>Try the student demo</h2><p>Continue with a simulated account built for this prototype.</p><label>Email<input type="email" value="aarav@example.test" readOnly/></label><label>Password<input type="password" value="synthetic-demo" readOnly/></label><button className="primary-btn full" type="submit">Continue securely <ArrowRight size={17}/></button><p className="form-note"><ShieldCheck size={15}/> Your choices are stored only in this browser.</p><button type="button" className="text-btn" onClick={() => { reset(); }}>Reset demo to first login</button></form></section></main><Footer/></div>
}

export function Onboarding() {
  const { state, setSelected, addExam } = useApp(); const nav = useNavigate(); const location = useLocation(); const adding = new URLSearchParams(location.search).get('mode') === 'add'
  const [query, setQuery] = useState(''); const [level, setLevel] = useState('All'); const [status, setStatus] = useState('All');
  const [picked, setPicked] = useState(adding ? [] : state.profile.selectedExamIds)
  const filtered = exams.filter(e => (!query || `${e.name} ${e.shortName} ${e.domain}`.toLowerCase().includes(query.toLowerCase())) && (level === 'All' || e.level === level) && (status === 'All' || e.registrationStatus === status) && (!adding || !state.profile.selectedExamIds.includes(e.id)))
  const toggle = id => setPicked(p => p.includes(id) ? p.filter(x => x !== id) : [...p, id])
  const finish = () => { if (!picked.length) return; if (adding) picked.forEach(addExam); else setSelected(picked); nav(`/workspace/${getExam(picked[0]).slug}`) }
  return <div className="app-page"><Header/><main className="onboarding"><div className="page-intro"><Link className="back-link" to={adding ? '/dashboard' : '/'}><ArrowLeft size={16}/> {adding ? 'Back to workspace' : 'Back to home'}</Link><span className="step-label">{adding ? 'EXPAND YOUR WORKSPACE' : 'STEP 1 OF 1'}</span><h1>{adding ? 'Add another examination' : 'Which examinations are you preparing for?'}</h1><p>Your selections create personalized workspaces. You can add or archive them later without losing saved application data.</p></div><div className="filter-bar"><label className="search-field"><Search/><span className="sr-only">Search examinations</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by exam, subject or purpose…"/></label><label><span className="sr-only">Level</span><select value={level} onChange={e=>setLevel(e.target.value)}><option>All</option><option>Undergraduate</option><option>Postgraduate</option></select></label><label><span className="sr-only">Registration status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option value="open">Open</option><option value="upcoming">Upcoming</option><option value="sample">Sample</option><option value="closed">Closed</option></select></label></div><div className="results-meta"><span>{filtered.length} examinations</span><span>Select one or more</span></div><div className="exam-grid">{filtered.map(exam => <ExamCard key={exam.id} exam={exam} selected={picked.includes(exam.id)} onToggle={() => toggle(exam.id)}/>)}</div>{!filtered.length && <EmptyState title="No matching examinations" body="Try a broader search or clear one of your filters."/>}</main><div className="selection-dock"><div><strong>{picked.length} {picked.length === 1 ? 'exam' : 'exams'} selected</strong><span>{picked.length ? picked.map(id => getExam(id)?.shortName).join(', ') : 'Choose at least one to continue'}</span></div><button className="primary-btn" disabled={!picked.length} onClick={finish}>Continue with selected exams <ArrowRight size={17}/></button></div></div>
}

export function Dashboard() {
  const { state } = useApp(); const selected = exams.filter(e => state.profile.selectedExamIds.includes(e.id))
  if (!selected.length) return <Navigate to="/onboarding/exams" replace/>
  const target = getExam(state.profile.activeExamId) || selected[0]
  return <Navigate to={`/workspace/${target.slug}`} replace/>
}

function WorkspaceNav({ exam, section }) {
  const items = [['desk', 'Exam Desk', GraduationCap], ['journey', 'My Journey', FileCheck2], ['explore', 'Explore More', Search]]
  return <nav className="workspace-nav" aria-label={`${exam.shortName} sections`}>{items.map(([id,label,Icon]) => <Link key={id} className={(section || 'desk') === id ? 'active' : ''} to={`/workspace/${exam.slug}/${id}`}><Icon size={18}/>{label}</Link>)}</nav>
}

export function Workspace() {
  const { examSlug, section = 'desk' } = useParams(); const { state, setActive } = useApp(); const exam = getExam(examSlug)
  if (!state.profile.selectedExamIds.length) return <Navigate to="/onboarding/exams" replace/>
  if (!exam || !state.profile.selectedExamIds.includes(exam.id)) return <Navigate to="/dashboard" replace/>
  if (state.profile.activeExamId !== exam.id) setTimeout(() => setActive(exam.id), 0)
  return <WorkspaceShell exam={exam}><main className="workspace-main"><div className="workspace-heading"><div><span className="eyebrow">{exam.level} · {exam.domain}</span><h2>{exam.shortName}</h2><p>{exam.purpose}</p></div><div><Status value={exam.registrationStatus}/><ExternalAnchor className="official-link" href={exam.officialUrl}>Official exam portal</ExternalAnchor></div></div><WorkspaceNav exam={exam} section={section}/>{section === 'journey' ? <Journey exam={exam}/> : section === 'explore' ? <Explore current={exam}/> : <Desk exam={exam}/>}</main><Footer/></WorkspaceShell>
}

function Desk({ exam }) {
  return <div className="workspace-content"><section className="milestone-banner"><div><span className="mini-label"><CalendarDays size={15}/> NEXT MILESTONE</span><h3>{exam.nextLabel || 'Official schedule to be announced'}</h3><p>{exam.nextDate ? `Sample date · ${new Date(exam.nextDate).toLocaleDateString('en-IN', {day:'numeric', month:'long', year:'numeric'})}` : 'Check the official portal for current information.'}</p></div><div className="countdown"><strong>{exam.nextDate ? Math.max(0, Math.ceil((new Date(exam.nextDate)-new Date())/86400000)) : '—'}</strong><span>days to go</span></div></section><div className="content-grid"><div className="main-column"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Updates for your exam</span><h3>Announcements</h3></div><Link to="/notices">View all <ChevronRight size={16}/></Link></div><div className="notice-list">{(exam.notices || []).map(n => <article key={n.title}><span className={n.urgent ? 'notice-icon urgent' : 'notice-icon'}><Megaphone/></span><div><div><span className="notice-type">{n.type}</span><time>{n.date}</time></div><h4>{n.title}</h4><small>Simulated notice for prototype demonstration</small></div></article>)}</div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Prepare</span><h3>Practice & papers</h3></div></div><div className="resource-grid">{(exam.resources || []).map((r,i)=><a key={r} href="/sample-paper.txt" download={`${exam.slug}-sample-resource.txt`}><span><FileText/><small>{i === 0 ? 'PRACTICE' : 'RESOURCE'}</small></span><strong>{r}</strong><em>Simulated download <Download size={15}/></em></a>)}</div></section></div><aside className="side-column"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Sample locations</span><h3>Nearby centres</h3></div><LocateFixed/></div><p className="muted">Example centres only. Final allocation appears on the official admit card.</p><ol className="center-list">{(exam.centers || []).map((c,i)=><li key={c}><span>{i+1}</span><div><strong>{c}</strong><small>{(3.2+i*2.7).toFixed(1)} km sample distance</small></div></li>)}</ol></section><section className="help-card"><HelpCircle/><div><strong>Need exam-specific help?</strong><p>Find official contact channels and safe guidance.</p><Link to="/help">Open help directory <ArrowRight size={15}/></Link></div></section></aside></div></div>
}

function Journey({ exam }) {
  const { state } = useApp(); const app = state.applications[exam.id] || { state: 'NOT_STARTED', currentStep: null, answers: {} }
  const steps = getSteps(exam); const done = app.state === 'SUBMITTED'; const pending = app.state === 'PAYMENT_PENDING'; const currentIndex = app.currentStep ? Math.max(0, steps.indexOf(app.currentStep)) : 0
  return <div className="workspace-content"><section className={`journey-callout ${pending ? 'warning' : ''}`}><div className="journey-icon">{pending ? <WalletCards/> : done ? <CheckCircle2/> : <FileCheck2/>}</div><div><span className="mini-label">YOUR APPLICATION</span><h3>{pending ? 'Payment needs your attention' : done ? 'Application submitted' : app.state === 'IN_PROGRESS' ? 'Continue where you left off' : 'Ready when you are'}</h3><p>{pending ? 'Your answers are safely saved. Retry the simulated payment to complete this application.' : done ? `Reference ${app.paymentReference}` : 'Review the pre-filled profile and complete this exam’s application steps.'}</p></div><Link className="primary-btn" to={`/apply/${exam.slug}/${pending ? 'payment' : currentIndex}`}>{pending ? 'Resume payment' : done ? 'View application' : app.state === 'IN_PROGRESS' ? 'Continue application' : 'Start application'} <ArrowRight size={17}/></Link></section><div className="content-grid"><section className="panel main-column"><div className="panel-head"><div><span className="eyebrow">Application path</span><h3>Your progress</h3></div><span className="progress-copy">{done ? steps.length : currentIndex} of {steps.length} complete</span></div><ol className="journey-steps">{steps.map((step,i)=>{const complete=done||i<currentIndex; const active=!done&&i===currentIndex; return <li className={complete?'complete':active?'active':''} key={step}><span>{complete?<Check/>:i+1}</span><div><strong>{step}</strong><small>{complete?'Completed':active?'Current step':'Upcoming'}</small></div></li>})}</ol></section><aside className="side-column"><section className="panel"><span className="eyebrow">Shared profile</span><h3>Reusable details</h3><div className="profile-summary"><span>AM</span><div><strong>{state.profile.name}</strong><small>{state.profile.email}</small><small>{state.profile.phone}</small></div></div><p className="muted">These account-level details are pre-filled, but you review them before every simulated submission.</p></section><section className="panel compact"><span className="eyebrow">Data boundary</span><p className="muted">Answers saved here belong only to {exam.shortName}. Switching exam tabs will not mix application data.</p></section></aside></div></div>
}

function Explore({ current }) {
  const { state, addExam } = useApp(); const [added, setAdded] = useState(null)
  const other = exams.filter(e => !state.profile.selectedExamIds.includes(e.id))
  return <div className="workspace-content"><div className="section-head simple"><div><span className="eyebrow">Discover more</span><h3>Other examinations you can track</h3><p>Adding one creates a new workspace without changing your {current.shortName} progress.</p></div><Link className="secondary-btn" to="/manage-exams">Manage exams</Link></div>{added && <div className="success-banner"><CheckCircle2/> {getExam(added).shortName} was added to your workspace.</div>}<div className="exam-grid compact-grid">{other.map(e=><ExamCard key={e.id} exam={e} selected={false} onToggle={()=>{addExam(e.id);setAdded(e.id)}} actionLabel="Add exam"/>)}</div>{!other.length&&<EmptyState title="Everything is in your workspace" body="You have added every examination in this demo catalogue."/>}</div>
}

export function ApplicationStep() {
  const { examSlug, step } = useParams(); const exam = getExam(examSlug); const { state, updateApplication } = useApp(); const nav = useNavigate()
  if (!exam || !state.profile.selectedExamIds.includes(exam.id)) return <Navigate to="/dashboard" replace/>
  const steps = getSteps(exam); const app = state.applications[exam.id] || { state:'NOT_STARTED', answers:{} }; const payment = step === 'payment'; const index = payment ? steps.length - 1 : Math.min(Number(step)||0, steps.length-1); const [fullName,setFullName]=useState(app.answers?.fullName || state.profile.name); const [confirmed,setConfirmed]=useState(false); const [payError,setPayError]=useState(false)
  const save = e => {e.preventDefault(); const last=index===steps.length-1; if(last){updateApplication(exam.id,{state:'PAYMENT_PENDING',currentStep:steps[index],answers:{...app.answers,fullName}});nav(`/apply/${exam.slug}/payment`)} else {updateApplication(exam.id,{state:'IN_PROGRESS',currentStep:steps[index+1],answers:{...app.answers,fullName}});nav(`/apply/${exam.slug}/${index+1}`)}}
  const pay = success => { if(!success){setPayError(true);updateApplication(exam.id,{state:'PAYMENT_PENDING'});return} updateApplication(exam.id,{state:'SUBMITTED',currentStep:null,paymentReference:`SIM-${exam.shortName.replace(/\W/g,'')}-260823`});nav(`/workspace/${exam.slug}/journey`) }
  return <div className="app-page"><Header/><main className="application-page"><Link className="back-link" to={`/workspace/${exam.slug}/journey`}><ArrowLeft size={16}/> Back to My Journey</Link><div className="application-layout"><aside><span className="eyebrow">SIMULATED APPLICATION</span><h1>{exam.shortName}</h1><ol>{steps.map((s,i)=><li className={i<index?'complete':i===index?'active':''} key={s}><span>{i<index?<Check/>:i+1}</span>{s}</li>)}</ol><div className="safe-note"><ShieldCheck/><p>No data is sent to NTA. This form exists only to demonstrate the journey.</p></div></aside>{payment ? <section className="form-panel"><span className="form-icon"><CreditCard/></span><span className="eyebrow">PAYMENT RECOVERY DEMO</span><h2>Complete simulated payment</h2><p>Your application answers are saved. Choose an outcome to test payment recovery.</p><div className="payment-summary"><span>Application fee <small>Sample amount</small></span><strong>₹1,000</strong></div>{payError&&<div className="error-banner"><AlertCircle/> Payment could not be completed. No amount was charged. Your application remains saved.</div>}<button className="primary-btn full" onClick={()=>pay(true)}>Simulate successful payment <ArrowRight size={17}/></button><button className="secondary-btn full" onClick={()=>pay(false)}>Simulate failed payment</button></section> : <form className="form-panel" onSubmit={save}><span className="eyebrow">STEP {index+1} OF {steps.length}</span><h2>{steps[index]}</h2><p>Review this synthetic information for the prototype.</p><label>Candidate name<input value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label>Email address<input value={state.profile.email} readOnly/></label>{index>0&&<label>Sample response<select defaultValue="confirmed"><option value="confirmed">Reviewed and confirmed</option><option>Needs correction</option></select></label>}<label className="check-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm that I reviewed this simulated information.</span></label><button className="primary-btn full" disabled={!confirmed||!fullName.trim()}>{index===steps.length-1?'Continue to payment':'Save and continue'} <ArrowRight size={17}/></button><button type="button" className="text-btn" onClick={()=>{updateApplication(exam.id,{state:'IN_PROGRESS',currentStep:steps[index],answers:{...app.answers,fullName}});nav(`/workspace/${exam.slug}/journey`)}}>Save and exit</button></form>}</div></main></div>
}

export function ManageExams() {
  const { state, archiveExam, restoreExam } = useApp(); const [confirm,setConfirm]=useState(null); const selected=exams.filter(e=>state.profile.selectedExamIds.includes(e.id)); const archived=exams.filter(e=>state.archivedExamIds.includes(e.id))
  return <div className="app-page"><Header/><main className="narrow-page"><Link className="back-link" to="/dashboard"><ArrowLeft size={16}/> Back to workspace</Link><div className="page-intro left"><span className="eyebrow">Workspace settings</span><h1>Manage examinations</h1><p>Archive a workspace to hide its tab. Saved application data remains available if you restore it later.</p></div><section className="panel"><div className="panel-head"><h2>Active workspaces</h2><Link className="primary-btn small" to="/onboarding/exams?mode=add">Add exam</Link></div>{selected.map(e=><div className="manage-row" key={e.id}><span className="exam-symbol" style={{background:`${e.color}18`,color:e.color}}>{e.shortName.slice(0,2)}</span><div><strong>{e.shortName}</strong><small>{e.purpose}</small></div><button className="danger-btn" onClick={()=>setConfirm(e)}>Archive</button></div>)}</section>{archived.length>0&&<section className="panel"><h2>Archived</h2>{archived.map(e=><div className="manage-row" key={e.id}><span className="exam-symbol">{e.shortName.slice(0,2)}</span><div><strong>{e.shortName}</strong><small>Application data retained</small></div><button className="secondary-btn small" onClick={()=>restoreExam(e.id)}>Restore</button></div>)}</section>}{confirm&&<div className="modal-backdrop" role="presentation"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><span className="warning-icon"><AlertCircle/></span><h2 id="confirm-title">Archive {confirm.shortName}?</h2><p>Its tab will be hidden, but all simulated application answers and progress will be kept.</p><div><button className="secondary-btn" onClick={()=>setConfirm(null)}>Keep workspace</button><button className="danger-solid" onClick={()=>{archiveExam(confirm.id);setConfirm(null)}}>Archive exam</button></div></div></div>}</main><Footer/></div>
}

function PublicLayout({children}) { return <div className="public-page"><Header/><main className="public-main">{children}</main><Footer/></div> }

export function ExamCatalogue() { const [q,setQ]=useState(''); const filtered=exams.filter(e=>`${e.name} ${e.domain} ${e.purpose}`.toLowerCase().includes(q.toLowerCase())); return <PublicLayout><div className="public-title"><span className="eyebrow">Exam catalogue</span><h1>Find the examination that fits your goal</h1><p>Explore sample metadata, then continue to the official portal for authoritative information.</p></div><label className="search-field standalone"><Search/><span className="sr-only">Search exams</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search examinations…"/></label><div className="exam-grid">{filtered.map(e=><ExamCard key={e.id} exam={e} selected={false} onToggle={()=>{}}/>)}</div></PublicLayout> }

export function Notices() { const [examId,setExamId]=useState('all'); const notices=deepExams.filter(e=>examId==='all'||e.id===examId).flatMap(e=>(e.notices||[]).map(n=>({...n,exam:e}))); return <PublicLayout><div className="public-title"><span className="eyebrow">Notice centre</span><h1>Relevant updates, minus the noise</h1><p>Small, simulated dataset for demonstrating exam filters. Always verify on the official portal.</p></div><div className="filter-bar one"><select value={examId} onChange={e=>setExamId(e.target.value)} aria-label="Filter by exam"><option value="all">All demo examinations</option>{deepExams.map(e=><option value={e.id} key={e.id}>{e.shortName}</option>)}</select></div><section className="panel public-list">{notices.map(n=><article key={`${n.exam.id}-${n.title}`}><span className="notice-icon"><Megaphone/></span><div><span className="notice-type">{n.exam.shortName} · {n.type}</span><h3>{n.title}</h3><small>{n.date} · Simulated notice</small></div><ExternalAnchor href={n.exam.officialUrl}>Verify officially</ExternalAnchor></article>)}</section></PublicLayout> }

export function Help() { return <PublicLayout><div className="public-title"><span className="eyebrow">Help directory</span><h1>Start with the right source</h1><p>Use official channels for application, eligibility and payment questions. This prototype does not provide case-specific decisions.</p></div><div className="help-grid"><section className="panel"><HelpCircle/><h2>Official NTA support</h2><p>Find current exam-specific contact details on NTA’s directory.</p><ExternalAnchor className="primary-btn" href="https://www.nta.ac.in/ContactUs">Open official directory</ExternalAnchor></section><section className="panel"><PlayCircle/><h2>Mock test help</h2><p>Learn how to use official CBT practice resources.</p><ExternalAnchor className="secondary-btn" href="https://nta.ac.in/Quiz">Open mock tests</ExternalAnchor></section><section className="panel"><BookOpen/><h2>Abhyas guidance</h2><p>Get support for practice tests and performance review.</p><ExternalAnchor className="secondary-btn" href="https://www.nta.ac.in/Abhyas/help">Open Abhyas help</ExternalAnchor></section></div></PublicLayout> }

export function About() { return <PublicLayout><div className="public-title"><span className="eyebrow">About the prototype</span><h1>A citizen-first concept, built independently</h1><p>This hackathon prototype explores a clearer, student-centred information architecture for multi-exam journeys.</p></div><div className="about-grid"><section className="panel"><h2>What is simulated</h2><p>Candidate identity, application numbers, dates, fees, centers, notices, answers and payment references are fictional. Browser storage is used for the demo.</p></section><section className="panel"><h2>What is official</h2><p>Clearly labeled external links lead to public NTA or exam websites. Those websites remain the authoritative source.</p></section><section className="panel"><h2>What we never do</h2><p>We do not log in to, scrape, imitate or send information to private government services.</p></section></div></PublicLayout> }
